name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_20bd1042-1275-42bb-b903-14389f4b4ce1 }}
          GH_TOKEN: ${{ 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 }}
